### ISSUE TITLE
Password Reset Error

### ISSUE THREAD

**Issue by greggmojica** [sebsylvester/parse-server-mailgun#10]
Password Reset throws the following error: requestPasswordReset: The server responded with a status of 500 Internal Server Error.

Any idea why this is occurring?

**Comment by sebsylvester** [comment]
I've just been able to complete the password reset flow, using the latest version of parse-server, so that rules out issues with the parse-server-mailgun module. 

It could occur because of some Cloud code function you've written, I really can't tell with the limited info you've provided. I suggest you debug the parse-server/lib/Routers/UsersRouter.js file by setting a breakpoint at the POST /requestPasswordReset handler and step through the code from there. Also set breakpoints in any relevant Cloud code functions.
