### ISSUE TITLE
Install fails on bcrypt 404.

### ISSUE THREAD

**Issue by majidhassan** [sebsylvester/parse-server-mailgun#16]
Hey,

I'm trying to install using: `npm install -g parse-server-mailgun` but the install fails due to a 404 on the bcrypt package. Below is the returned stacktrace.

```
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.7.2 (node-v46 ABI) (falling back to source compile with node-gyp)
```

**Comment by sebsylvester** [comment]
I think it's because I've added parse-server as a dependency. The MailgunAdapter extends the MailAdapter class, so it was wrong not to include it as a dep. SInce the adapter is supposed te be used exclusively with parse-server, this dependency is supposed to be installed already, so I didn't think it was a big deal to add it. Of course this does not take into account global installs of the adapter. 

About the error itself. I don't think there's anything I can do about it as I believe it results directly from installing the parse-server package as part of the global install of parse-server-adapter.

**Comment by majidhassan** [comment]
Hey Sebastian,

Thanks for the fast reply. I'm not sure I'm following, though. Does this mean the parse-server-mailgun adapter comes preinstalled with parse-server? If not how do I properly install it with parse-server then?

**Comment by sebsylvester** [comment]
Hi, 
No, the adapter does not come preinstalled with parse-server. But since the parse-server is now a dependency of parse-server-mailgun. When adding the adapter to your project or installing it globally, npm will now check if the parse-server is present. The error you encounter is related to the installation of the parse-server module, because that's the only dependency that needs bcrypt.

**Comment by sebsylvester** [comment]
Hi, just wanted to let you know that I've encountered the exact same error when installing parse-server globally. I think it's an issue that the maintainers of parse-server should look into. Until it's fixed you could still use the pre-installed parse-server-simple-mailgun-adapter.
