### ISSUE TITLE
Multi language in template support

### ISSUE THREAD

**Issue by tvpsoft** [sebsylvester/parse-server-mailgun#25]
Hello, 
How can I use Parse-Server-Mailgun with multi language support?
Thanks.

**Comment by sebsylvester** [comment]
Hi, 
I suppose you're referring to the password reset and account creation emails only, because the direct usage of the adapter allows you to select any of the configured templates. 
Multi-language emails was not a requirement that I considered when building the module but I think this hack should solve your problem. 

Make sure the user's preferred language has previously been saved to MongoDB and configure additional templates for each language, then add this to the code:
```
sendPasswordResetEmail({ link, appName, user }) {
   const lang = user.get("lang"); // or any other field name you want to use for the language value
   // Update the templateName property   
   return this._sendMail({ templateName: `passwordResetEmail_${lang}`, link, appName, user });
}
```
