### ISSUE TITLE
Mailgun Adapter Not Sending Emails

### ISSUE THREAD

**Issue by fprospato** [sebsylvester/parse-server-mailgun#38]
Hello,
I set up my parse server for my iOS project using AWS with Bitnami. I added this to my server.js file:

```
verifyUserEmails: true,
publicServerURL: 'https://ec2../parse',
appName: 'name',
emailAdapter: {
module: 'parse-server-simple-mailgun-adapter',
options: {
fromAddress: ADDRESS',
domain: 'DOMAIN',
apiKey: 'KEY'
```
I thought that this was it, but when I sign up a user or try to reset a password, I do not get an email. The address, domain, and api key are all correct. I saw that somehow we are suppose to install the adapter through 'npm'. I have never installed something with npm before and do not know how to. I get access to my server through connecting to my instance by launching my SSH Client. How do I go from there to just add/install `npm i parse-server-mailgun` properly?

I have been working on this mailgun integration for months and I am in desperate need for help. So if anyone can give me any help I will be forever grateful!

**Comment by sebsylvester** [comment]
Hi,
First of all, I noticed that you're not referencing the correct module: it should be `parse-server-mailgun` instead of `parse-server-simple-mailgun-adapter`. Second, you will need to add `parse-server-mailgun` to your `package.json` file as a dependency. Lastly, make sure you run `npm install` on your server from the same directory as `package.json`.
